# Generated by Django 5.1.7 on 2025-03-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNr', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=4)),
                ('shape', models.CharField(choices=[('Long', 'Long'), ('Round', 'Round')], default='Round', max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('confirmID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_start', models.TimeField(blank=True, null=True)),
                ('booking_end', models.TimeField(blank=True, null=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
    ]
